# Generated by Django 5.2.6 on 2025-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='resolved_on',
            field=models.DateField(blank=True, null=True, verbose_name='Resolved On'),
        ),
    ]
